apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  mongo-username: {{ .Values.mongo.username | b64enc }}
  mongo-password: {{ .Values.mongo.password | b64enc }}
