apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-agent
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-agent
  template:
    metadata:
      labels:
        app: prefect-agent
    spec:
      serviceAccountName: prefect-agent
      containers:
      - name: prefect-agent
        image: {{ .Values.prefect.image }}
        resources:
          {{- toYaml .Values.prefect.resources | nindent 10 }}
