apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init-job
  namespace: {{ .Values.global.namespace }}
spec:
  template:
    spec:
      containers:
      - name: mongo-init
        image: {{ .Values.mongo.image }}
        command: ["mongo", "--eval", "db.getSiblingDB('{{ .Values.mongo.database }}').createCollection('init')"]
      restartPolicy: OnFailure
