apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: connector-network-policy
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - {}
